id = 0
title = "The first series in this blog"

[[content]]
subname = "the first title"
date = 2024-05-19
description = "The first in a series"
content = "source1.md"
id = 0

[[content]]
subname = "the second title"
date = 2024-05-20
description = "The second in a series"
content = "source2.md"
id = 1